Repository intake/intake-thredds, pull requests merged in 2022-01, with the labels that each got.

#63 check `type` of `path`
  intake_thredds/source.py
  tests/test_source.py
Labels: enhancement, documentation

#66 Remove linting workflow
  .github/workflows/linting.yaml
  README.md
Labels: maintenance, CI

#68 Update refs: NCAR/intake-thredds -> intake/intake-thredds
  .github/workflows/ci.yaml
  .github/workflows/pypi.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/source/conf.py
  docs/source/index.md
  setup.py
Labels: CI

#69 Add pyupgrade to the list of pre-commit hooks
  .pre-commit-config.yaml
  docs/source/conf.py
  intake_thredds/source.py
  pyproject.toml
  setup.cfg
  setup.py
  tests/test_source.py
Labels: maintenance, CI
